[tools]
bun = ["latest"]
deno = ["latest"]
elixir = ["latest"]
erlang = ["latest"]
go = ["latest"]
java = ["17","21","11","liberica-8u472+11"]
node = ["latest","24","22","18"]
python = ["3"]
ruby = ["latest","3.3.5","3.4"]
rust = ["latest"]
zig = ["latest"]
zls = ["latest"]

[settings]
idiomatic_version_file_enable_tools = []
